# Generated by Django 5.2 on 2025-04-17 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Контакт Компании",
                "verbose_name_plural": "Контакты Компании",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Контактный email адрес",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="office_address",
            field=models.CharField(
                blank=True,
                help_text="Физический адрес офиса",
                max_length=255,
                verbose_name="Адрес офиса",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона в формате +7 XXX XXX XX XX",
                max_length=20,
                verbose_name="Контактный телефон",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Номер WhatsApp, связанный с компанией",
                max_length=20,
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="contacts.contact",
                verbose_name="Контакт Компании",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Время окончания рабочего дня (ЧЧ:ММ)",
                null=True,
                verbose_name="Время окончания работы",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, если это рабочий день. Если не отмечено, считается выходным.",
                verbose_name="Рабочий день",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Время начала рабочего дня (ЧЧ:ММ)",
                null=True,
                verbose_name="Время начала работы",
            ),
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя отправителя"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email отправителя"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон отправителя"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Тема сообщения"
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("in_progress", "В обработке"),
                            ("closed", "Закрыт"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления статуса"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (если известен)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос с контактной формы",
                "verbose_name_plural": "Запросы с контактной формы",
                "ordering": ["-created_at"],
            },
        ),
    ]
