# Generated by Django 5.2 on 2025-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landplot",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счетчик просмотров"
            ),
        ),
        migrations.AddField(
            model_name="listingcomplex",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счетчик просмотров"
            ),
        ),
        migrations.AddField(
            model_name="listingunit",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счетчик просмотров"
            ),
        ),
    ]
