# Generated by Django 5.2 on 2025-04-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя клиента")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email клиента",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Квиз"),
                            ("contact", "Контактная форма"),
                            ("listing", "Объявление"),
                        ],
                        max_length=10,
                        verbose_name="Тип заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID связанного объекта"
                    ),
                ),
                (
                    "quiz_answers",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ответы на квиз"
                    ),
                ),
                (
                    "user_message",
                    models.TextField(blank=True, verbose_name="Сообщение пользователя"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Тип связанного объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_comments",
                        to="requests_app.request",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий администратора",
                "verbose_name_plural": "Комментарии администраторов",
                "ordering": ["created_at"],
            },
        ),
    ]
