# Generated by Django 5.2 on 2025-04-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("communication", "Коммуникация участка"),
                            ("plot_feature", "Особенность участка"),
                            ("complex_infrastructure", "Инфраструктура комплекса"),
                            ("unit_feature", "Особенность юнита (отделка и т.п.)"),
                        ],
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность/Характеристика",
                "verbose_name_plural": "Особенности/Характеристики",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="LandCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название категории земель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория земель",
                "verbose_name_plural": "Категории земель",
            },
        ),
        migrations.CreateModel(
            name="LandUseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название ВРИ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Вид разрешенного использования (ВРИ)",
                "verbose_name_plural": "Виды разрешенного использования (ВРИ)",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Регион")),
                (
                    "locality",
                    models.CharField(max_length=100, verbose_name="Населенный пункт"),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Улица, дом и т.д."
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение",
                "verbose_name_plural": "Местоположения",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название типа"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="Slug типа",
                    ),
                ),
                (
                    "attribute_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Определите поля для этого типа недвижимости в формате JSON",
                        verbose_name="Схема атрибутов (JSON)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип объекта недвижимости",
                "verbose_name_plural": "Типы объектов недвижимости",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LandPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартный участок"),
                            ("new_territory", "Новообразованная территория"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Тип участка",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="Slug (ЧПУ)",
                    ),
                ),
                (
                    "cadastral_numbers",
                    models.TextField(
                        blank=True,
                        verbose_name="Кадастровые номера (через запятую или JSON)",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Площадь (в сотках)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена (руб.)"
                    ),
                ),
                (
                    "price_per_are",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена за сотку (руб.)",
                    ),
                ),
                (
                    "plot_status",
                    models.CharField(
                        choices=[
                            ("available", "Доступен"),
                            ("sold", "Продан"),
                            ("reserved", "Бронь"),
                        ],
                        default="available",
                        max_length=10,
                        verbose_name="Статус участка",
                    ),
                ),
                (
                    "listing_status",
                    models.CharField(
                        choices=[("published", "Опубликовано"), ("hidden", "Скрыто")],
                        default="hidden",
                        max_length=10,
                        verbose_name="Статус объявления",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "type__in": ["communication", "plot_feature"]
                        },
                        related_name="land_plots",
                        to="catalog.feature",
                        verbose_name="Коммуникации и особенности",
                    ),
                ),
                (
                    "land_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_plots",
                        to="catalog.landcategory",
                        verbose_name="Категория земель",
                    ),
                ),
                (
                    "land_use_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="land_plots",
                        to="catalog.landusetype",
                        verbose_name="ВРИ",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_plots",
                        to="catalog.location",
                        verbose_name="Местоположение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Земельный участок",
                "verbose_name_plural": "Земельные участки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(upload_to="listings_media/", verbose_name="Файл"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("document", "Документ"),
                            ("plan", "Планировка"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Главный файл (обложка)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание файла"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиафайл",
                "verbose_name_plural": "Медиафайлы",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GenericProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="Slug (ЧПУ)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена (руб.)"
                    ),
                ),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("published", "Опубликовано"),
                            ("hidden", "Скрыто"),
                            ("sold", "Продано"),
                            ("reserved", "Бронь"),
                        ],
                        default="hidden",
                        max_length=10,
                        verbose_name="Статус объявления",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Значения атрибутов согласно схеме типа объекта",
                        verbose_name="Атрибуты объекта",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.genericproperty",
                        verbose_name="Родительский объект (комплекс)",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_properties",
                        to="catalog.location",
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.propertytype",
                        verbose_name="Тип объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект недвижимости (универсальный)",
                "verbose_name_plural": "Объекты недвижимости (универсальные)",
                "ordering": ["-created_at"],
            },
        ),
    ]
