# Generated by Django 5.2 on 2025-04-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericproperty",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generic_properties",
                to="catalog.location",
                verbose_name="Местоположение",
            ),
        ),
        migrations.AlterField(
            model_name="genericproperty",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="catalog.genericproperty",
                verbose_name="Родительский объект (комплекс)",
            ),
        ),
        migrations.AlterField(
            model_name="genericproperty",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="catalog.propertytype",
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["communication", "plot_feature"]},
                related_name="land_plots",
                to="catalog.feature",
                verbose_name="Коммуникации и особенности",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="land_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_plots",
                to="catalog.landcategory",
                verbose_name="Категория земель",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="land_use_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="land_plots",
                to="catalog.landusetype",
                verbose_name="ВРИ",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_plots",
                to="catalog.location",
                verbose_name="Местоположение",
            ),
        ),
    ]
