# Generated by Django 5.2 on 2025-04-18 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_genericproperty_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="landplot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="land_plots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец/Агент",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="area",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                verbose_name="Площадь (в сотках)",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="listing_status",
            field=models.CharField(
                choices=[("published", "Опубликовано"), ("hidden", "Скрыто")],
                db_index=True,
                default="hidden",
                max_length=10,
                verbose_name="Статус объявления",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=15,
                verbose_name="Цена (руб.)",
            ),
        ),
        migrations.AlterField(
            model_name="landplot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
