# Generated by Django 5.2 on 2025-04-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_landplot_owner_alter_landplot_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericproperty",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="landplot",
            name="owner",
        ),
    ]
